from engine.score import aggregate

PSL_MIN = 1.0
PSL_MAX = 10.0
MIN_TIER_GAP = 0.4


def test_all_samples_stay_inside_scale():
    for values in _all_samples():
        psl = aggregate(values, "frontal", "male")["psl"]
        assert PSL_MIN <= psl <= PSL_MAX


def test_balanced_sample_scores_above_weak_sample():
    balanced = aggregate(_balanced_sample_values(), "frontal", "male")
    weak = aggregate(_weak_sample_values(), "frontal", "male")
    assert balanced["psl"] > weak["psl"] + MIN_TIER_GAP


def test_severe_defects_sample_is_the_lowest_tier():
    severe = aggregate(_severe_defects_sample_values(), "frontal", "male")["psl"]
    for values in _all_samples():
        if values == _severe_defects_sample_values():
            continue
        assert aggregate(values, "frontal", "male")["psl"] >= severe


def test_low_skin_sample_scores_below_same_face_with_clean_skin():
    low_skin = aggregate(_low_skin_sample_values(), "frontal", "male")
    clean_skin = aggregate(_second_balanced_sample_values(), "frontal", "male")
    assert low_skin["psl"] < clean_skin["psl"]


def test_disabled_metric_changes_nothing_when_metric_is_absent():
    values = _balanced_sample_values()
    full = aggregate(values, "frontal", "male")
    filtered = aggregate(values, "frontal", "male", {"metric_that_does_not_exist"})
    assert full["psl"] == filtered["psl"]


def _all_samples():
    return [
        _balanced_sample_values(),
        _second_balanced_sample_values(),
        _third_balanced_sample_values(),
        _mid_tier_sample_values(),
        _weak_sample_values(),
        _low_skin_sample_values(),
        _mixed_defects_sample_values(),
        _severe_defects_sample_values(),
    ]


def _balanced_sample_values():
    return {
        "fwhr": 1.92,
        "fwhr_mid": 2.72,
        "facial_index": 0.84,
        "facial_thirds": 41.3,
        "lower_third_ratio": 0.56,
        "midface_ratio": 1.10,
        "lip_ratio": 1.65,
        "bigonial_bizygomatic": 0.88,
        "chin_philtrum": 2.27,
        "mouth_nose": 1.52,
        "esr": 0.47,
        "eye_spacing": 1.09,
        "pfl_pfh": 3.52,
        "canthal_tilt": 2.9,
        "eme_angle": 48.9,
        "brow_tilt": -3.1,
        "jaw_frontal_angle": 88.0,
        "symmetry": 98.3,
        "skin": 77.22,
        "jaw_mid_width_ratio": 0.81,
        "jaw_low_width_ratio": 0.66,
        "chin_width_ratio": 0.47,
        "jaw_taper_ratio": 0.53,
        "mandible_taper_ratio": 0.82,
        "lower_face_width_height": 1.89,
        "chin_height_face_ratio": 0.27,
        "philtrum_face_ratio": 0.12,
        "mouth_chin_face_ratio": 0.38,
        "upper_lip_face_ratio": 0.07,
        "lower_lip_face_ratio": 0.11,
        "mouth_width_face_ratio": 0.35,
        "nose_width_face_ratio": 0.23,
        "nose_height_face_ratio": 0.44,
        "nose_height_width_ratio": 1.59,
        "nose_mouth_balance": 0.66,
        "eye_width_face_ratio": 0.18,
        "eye_height_face_ratio": 0.05,
        "outer_eye_width_ratio": 0.64,
        "intercanthal_face_ratio": 0.29,
        "eye_area_ratio": 0.02,
        "eye_size_symmetry": 1.0,
        "eye_height_symmetry": 0.97,
        "canthal_symmetry": 1.0,
        "brow_eye_gap_ratio": 2.45,
        "brow_length_eye_ratio": 1.90,
        "brow_inner_gap_ratio": 0.19,
        "brow_eye_tilt_delta": 6.0,
        "mouth_symmetry": 0.91,
        "nose_symmetry": 0.95,
        "jaw_symmetry": 0.96,
    }


def _low_skin_sample_values():
    return {
        "fwhr": 2.14,
        "fwhr_mid": 2.98,
        "facial_index": 0.79,
        "facial_thirds": 40.4,
        "lower_third_ratio": 0.58,
        "midface_ratio": 1.11,
        "lip_ratio": 1.50,
        "bigonial_bizygomatic": 0.92,
        "chin_philtrum": 2.97,
        "mouth_nose": 1.71,
        "esr": 0.43,
        "eye_spacing": 1.32,
        "pfl_pfh": 3.64,
        "canthal_tilt": 6.3,
        "eme_angle": 48.5,
        "brow_tilt": 3.2,
        "jaw_frontal_angle": 93.8,
        "symmetry": 97.9,
        "skin": 55.19,
        "jaw_mid_width_ratio": 0.84,
        "jaw_low_width_ratio": 0.68,
        "chin_width_ratio": 0.49,
        "jaw_taper_ratio": 0.53,
        "mandible_taper_ratio": 0.81,
        "lower_face_width_height": 2.02,
        "chin_height_face_ratio": 0.32,
        "philtrum_face_ratio": 0.11,
        "mouth_chin_face_ratio": 0.41,
        "upper_lip_face_ratio": 0.06,
        "lower_lip_face_ratio": 0.09,
        "mouth_width_face_ratio": 0.34,
        "nose_width_face_ratio": 0.20,
        "nose_height_face_ratio": 0.42,
        "nose_height_width_ratio": 1.68,
        "nose_mouth_balance": 0.58,
        "eye_width_face_ratio": 0.17,
        "eye_height_face_ratio": 0.05,
        "outer_eye_width_ratio": 0.59,
        "intercanthal_face_ratio": 0.26,
        "eye_area_ratio": 0.02,
        "eye_size_symmetry": 0.94,
        "eye_height_symmetry": 0.91,
        "canthal_symmetry": 0.1,
        "brow_eye_gap_ratio": 2.02,
        "brow_length_eye_ratio": 1.96,
        "brow_inner_gap_ratio": 0.17,
        "brow_eye_tilt_delta": 3.1,
        "mouth_symmetry": 0.96,
        "nose_symmetry": 0.95,
        "jaw_symmetry": 0.91,
    }


def _mixed_defects_sample_values():
    return {
        "fwhr": 1.98,
        "fwhr_mid": 2.89,
        "facial_index": 0.79,
        "facial_thirds": 41.2,
        "lower_third_ratio": 0.56,
        "midface_ratio": 1.04,
        "lip_ratio": 1.35,
        "bigonial_bizygomatic": 0.87,
        "chin_philtrum": 2.09,
        "mouth_nose": 1.30,
        "esr": 0.48,
        "eye_spacing": 1.09,
        "pfl_pfh": 2.83,
        "canthal_tilt": 5.2,
        "eme_angle": 51.4,
        "brow_tilt": 1.2,
        "jaw_frontal_angle": 91.6,
        "symmetry": 95.1,
        "skin": 71.71,
        "jaw_mid_width_ratio": 0.77,
        "jaw_low_width_ratio": 0.63,
        "chin_width_ratio": 0.46,
        "jaw_taper_ratio": 0.53,
        "mandible_taper_ratio": 0.82,
        "lower_face_width_height": 1.98,
        "chin_height_face_ratio": 0.26,
        "philtrum_face_ratio": 0.12,
        "mouth_chin_face_ratio": 0.36,
        "upper_lip_face_ratio": 0.08,
        "lower_lip_face_ratio": 0.11,
        "mouth_width_face_ratio": 0.30,
        "nose_width_face_ratio": 0.23,
        "nose_height_face_ratio": 0.44,
        "nose_height_width_ratio": 1.49,
        "nose_mouth_balance": 0.77,
        "eye_width_face_ratio": 0.21,
        "eye_height_face_ratio": 0.07,
        "outer_eye_width_ratio": 0.68,
        "intercanthal_face_ratio": 0.27,
        "eye_area_ratio": 0.04,
        "eye_size_symmetry": 0.91,
        "eye_height_symmetry": 0.96,
        "canthal_symmetry": 1.1,
        "brow_eye_gap_ratio": 1.92,
        "brow_length_eye_ratio": 1.78,
        "brow_inner_gap_ratio": 0.16,
        "brow_eye_tilt_delta": 4.0,
        "mouth_symmetry": 0.66,
        "nose_symmetry": 0.75,
        "jaw_symmetry": 0.94,
    }


def _mid_tier_sample_values():
    return {
        "fwhr": 2.11,
        "fwhr_mid": 3.03,
        "facial_index": 0.81,
        "facial_thirds": 40.2,
        "lower_third_ratio": 0.59,
        "midface_ratio": 1.03,
        "lip_ratio": 1.67,
        "bigonial_bizygomatic": 0.87,
        "chin_philtrum": 2.68,
        "mouth_nose": 1.60,
        "esr": 0.45,
        "eye_spacing": 1.09,
        "pfl_pfh": 3.69,
        "canthal_tilt": 1.7,
        "eme_angle": 51.8,
        "brow_tilt": -11.0,
        "jaw_frontal_angle": 96.5,
        "symmetry": 95.5,
        "skin": 69.11,
        "jaw_mid_width_ratio": 0.79,
        "jaw_low_width_ratio": 0.63,
        "chin_width_ratio": 0.44,
        "jaw_taper_ratio": 0.50,
        "mandible_taper_ratio": 0.80,
        "lower_face_width_height": 1.82,
        "chin_height_face_ratio": 0.32,
        "philtrum_face_ratio": 0.12,
        "mouth_chin_face_ratio": 0.42,
        "upper_lip_face_ratio": 0.06,
        "lower_lip_face_ratio": 0.10,
        "mouth_width_face_ratio": 0.36,
        "nose_width_face_ratio": 0.23,
        "nose_height_face_ratio": 0.41,
        "nose_height_width_ratio": 1.46,
        "nose_mouth_balance": 0.62,
        "eye_width_face_ratio": 0.19,
        "eye_height_face_ratio": 0.05,
        "outer_eye_width_ratio": 0.63,
        "intercanthal_face_ratio": 0.26,
        "eye_area_ratio": 0.02,
        "eye_size_symmetry": 0.95,
        "eye_height_symmetry": 0.90,
        "canthal_symmetry": 0.5,
        "brow_eye_gap_ratio": 2.60,
        "brow_length_eye_ratio": 1.95,
        "brow_inner_gap_ratio": 0.17,
        "brow_eye_tilt_delta": 12.7,
        "mouth_symmetry": 0.72,
        "nose_symmetry": 0.84,
        "jaw_symmetry": 0.92,
    }


def _second_balanced_sample_values():
    return {
        "fwhr": 1.88,
        "fwhr_mid": 2.63,
        "facial_index": 0.84,
        "facial_thirds": 37.7,
        "lower_third_ratio": 0.55,
        "midface_ratio": 1.12,
        "lip_ratio": 1.63,
        "bigonial_bizygomatic": 0.86,
        "chin_philtrum": 2.24,
        "mouth_nose": 1.55,
        "esr": 0.47,
        "eye_spacing": 1.07,
        "pfl_pfh": 3.89,
        "canthal_tilt": 5.5,
        "eme_angle": 48.0,
        "brow_tilt": 0.5,
        "jaw_frontal_angle": 85.4,
        "symmetry": 97.5,
        "skin": 73.47,
        "jaw_mid_width_ratio": 0.79,
        "jaw_low_width_ratio": 0.65,
        "chin_width_ratio": 0.47,
        "jaw_taper_ratio": 0.54,
        "mandible_taper_ratio": 0.82,
        "lower_face_width_height": 1.87,
        "chin_height_face_ratio": 0.26,
        "philtrum_face_ratio": 0.12,
        "mouth_chin_face_ratio": 0.37,
        "upper_lip_face_ratio": 0.07,
        "lower_lip_face_ratio": 0.11,
        "mouth_width_face_ratio": 0.36,
        "nose_width_face_ratio": 0.23,
        "nose_height_face_ratio": 0.45,
        "nose_height_width_ratio": 1.65,
        "nose_mouth_balance": 0.65,
        "eye_width_face_ratio": 0.18,
        "eye_height_face_ratio": 0.05,
        "outer_eye_width_ratio": 0.64,
        "intercanthal_face_ratio": 0.28,
        "eye_area_ratio": 0.02,
        "eye_size_symmetry": 0.97,
        "eye_height_symmetry": 0.89,
        "canthal_symmetry": 1.2,
        "brow_eye_gap_ratio": 2.81,
        "brow_length_eye_ratio": 1.83,
        "brow_inner_gap_ratio": 0.20,
        "brow_eye_tilt_delta": 4.9,
        "mouth_symmetry": 0.71,
        "nose_symmetry": 0.68,
        "jaw_symmetry": 0.94,
    }


def _third_balanced_sample_values():
    return {
        "fwhr": 2.14,
        "fwhr_mid": 3.13,
        "facial_index": 0.76,
        "facial_thirds": 40.8,
        "lower_third_ratio": 0.58,
        "midface_ratio": 1.06,
        "lip_ratio": 1.86,
        "bigonial_bizygomatic": 0.88,
        "chin_philtrum": 2.01,
        "mouth_nose": 1.71,
        "esr": 0.44,
        "eye_spacing": 1.23,
        "pfl_pfh": 3.52,
        "canthal_tilt": 5.6,
        "eme_angle": 50.4,
        "brow_tilt": 0.0,
        "jaw_frontal_angle": 95.3,
        "symmetry": 98.0,
        "skin": 73.40,
        "jaw_mid_width_ratio": 0.80,
        "jaw_low_width_ratio": 0.63,
        "chin_width_ratio": 0.45,
        "jaw_taper_ratio": 0.51,
        "mandible_taper_ratio": 0.80,
        "lower_face_width_height": 2.00,
        "chin_height_face_ratio": 0.29,
        "philtrum_face_ratio": 0.14,
        "mouth_chin_face_ratio": 0.38,
        "upper_lip_face_ratio": 0.05,
        "lower_lip_face_ratio": 0.09,
        "mouth_width_face_ratio": 0.32,
        "nose_width_face_ratio": 0.19,
        "nose_height_face_ratio": 0.42,
        "nose_height_width_ratio": 1.70,
        "nose_mouth_balance": 0.58,
        "eye_width_face_ratio": 0.17,
        "eye_height_face_ratio": 0.05,
        "outer_eye_width_ratio": 0.60,
        "intercanthal_face_ratio": 0.27,
        "eye_area_ratio": 0.02,
        "eye_size_symmetry": 0.93,
        "eye_height_symmetry": 0.91,
        "canthal_symmetry": 3.4,
        "brow_eye_gap_ratio": 2.30,
        "brow_length_eye_ratio": 1.99,
        "brow_inner_gap_ratio": 0.19,
        "brow_eye_tilt_delta": 5.6,
        "mouth_symmetry": 0.88,
        "nose_symmetry": 1.0,
        "jaw_symmetry": 0.95,
    }


def _severe_defects_sample_values():
    return {
        "fwhr": 2.20,
        "fwhr_mid": 3.50,
        "facial_index": 0.80,
        "facial_thirds": None,
        "lower_third_ratio": 0.64,
        "midface_ratio": 0.90,
        "lip_ratio": 1.08,
        "bigonial_bizygomatic": 0.92,
        "chin_philtrum": 2.82,
        "mouth_nose": 1.31,
        "esr": 0.44,
        "eye_spacing": 1.24,
        "pfl_pfh": 9.60,
        "canthal_tilt": -6.3,
        "eme_angle": 57.9,
        "brow_tilt": None,
        "jaw_frontal_angle": 112.4,
        "symmetry": 97.5,
        "skin": 83.24,
        "jaw_mid_width_ratio": 0.83,
        "jaw_low_width_ratio": 0.66,
        "chin_width_ratio": 0.47,
        "jaw_taper_ratio": 0.51,
        "mandible_taper_ratio": 0.80,
        "lower_face_width_height": 1.80,
        "chin_height_face_ratio": 0.33,
        "philtrum_face_ratio": 0.12,
        "mouth_chin_face_ratio": 0.43,
        "upper_lip_face_ratio": 0.09,
        "lower_lip_face_ratio": 0.10,
        "mouth_width_face_ratio": 0.34,
        "nose_width_face_ratio": 0.26,
        "nose_height_face_ratio": 0.36,
        "nose_height_width_ratio": 1.12,
        "nose_mouth_balance": 0.76,
        "eye_width_face_ratio": 0.17,
        "eye_height_face_ratio": 0.02,
        "outer_eye_width_ratio": 0.61,
        "intercanthal_face_ratio": 0.27,
        "eye_area_ratio": 0.01,
        "eye_size_symmetry": 0.92,
        "eye_height_symmetry": 0.79,
        "canthal_symmetry": 0.9,
        "brow_eye_gap_ratio": 9.85,
        "brow_length_eye_ratio": 2.03,
        "brow_inner_gap_ratio": 0.14,
        "brow_eye_tilt_delta": None,
        "mouth_symmetry": 0.94,
        "nose_symmetry": 0.97,
        "jaw_symmetry": 0.97,
    }


def _weak_sample_values():
    return {
        "fwhr": 1.83,
        "fwhr_mid": 2.46,
        "facial_index": 0.81,
        "facial_thirds": None,
        "lower_third_ratio": 0.50,
        "midface_ratio": 1.14,
        "lip_ratio": 1.79,
        "bigonial_bizygomatic": 0.88,
        "chin_philtrum": 1.88,
        "mouth_nose": 1.49,
        "esr": 0.47,
        "eye_spacing": 1.10,
        "pfl_pfh": 4.09,
        "canthal_tilt": 6.7,
        "eme_angle": 47.3,
        "brow_tilt": -2.4,
        "jaw_frontal_angle": 94.0,
        "symmetry": 96.5,
        "skin": 75.55,
        "jaw_mid_width_ratio": 0.77,
        "jaw_low_width_ratio": 0.61,
        "chin_width_ratio": 0.44,
        "jaw_taper_ratio": 0.50,
        "mandible_taper_ratio": 0.80,
        "lower_face_width_height": 2.18,
        "chin_height_face_ratio": 0.23,
        "philtrum_face_ratio": 0.12,
        "mouth_chin_face_ratio": 0.32,
        "upper_lip_face_ratio": 0.05,
        "lower_lip_face_ratio": 0.09,
        "mouth_width_face_ratio": 0.39,
        "nose_width_face_ratio": 0.26,
        "nose_height_face_ratio": 0.50,
        "nose_height_width_ratio": 1.56,
        "nose_mouth_balance": 0.67,
        "eye_width_face_ratio": 0.19,
        "eye_height_face_ratio": 0.05,
        "outer_eye_width_ratio": 0.65,
        "intercanthal_face_ratio": 0.28,
        "eye_area_ratio": 0.02,
        "eye_size_symmetry": 0.97,
        "eye_height_symmetry": 0.97,
        "canthal_symmetry": 0.2,
        "brow_eye_gap_ratio": 3.12,
        "brow_length_eye_ratio": 1.93,
        "brow_inner_gap_ratio": 0.16,
        "brow_eye_tilt_delta": 9.1,
        "mouth_symmetry": 0.92,
        "nose_symmetry": 0.98,
        "jaw_symmetry": 0.82,
    }
